const NAV_CONFIGS = {
  _trade: [
    { path:'/dashboard',       icon:'📊', key:'nav.dashboard'      },
    { path:'/inventory',       icon:'📦', key:'nav.inventory'      },
    { path:'/suppliers',       icon:'🚛', key:'nav.suppliers'      },
    { path:'/purchase-orders', icon:'🛒', key:'nav.purchaseOrders' },
    { path:'/customers',       icon:'👥', key:'nav.customers'      },
    null,
    { path:'/accounting',      icon:'💰', key:'nav.accounting'     },
    { path:'/warehouses',      icon:'🏭', key:'nav.warehouses'     },
    { path:'/employees',       icon:'👤', key:'nav.employees'      },
    { path:'/branches',        icon:'🏪', key:'nav.branches'       },
  ],
  hotel: [
    { path:'/dashboard', icon:'📊', key:'nav.dashboard' },
    { path:'/rooms',     icon:'🛏️', key:'nav.rooms'     },
    { path:'/bookings',  icon:'📅', key:'nav.bookings'  },
    { path:'/customers', icon:'👥', key:'nav.guests'    },
    null,
    { path:'/accounting',icon:'💰', key:'nav.accounting'},
    { path:'/employees', icon:'👤', key:'nav.employees' },
    { path:'/inventory', icon:'📦', key:'nav.inventory' },
  ],
  furnished_apartments: [
    { path:'/dashboard', icon:'📊', key:'nav.dashboard' },
    { path:'/rooms',     icon:'🏠', key:'nav.units'     },
    { path:'/bookings',  icon:'📅', key:'nav.bookings'  },
    { path:'/customers', icon:'👥', key:'nav.tenants'   },
    null,
    { path:'/accounting',icon:'💰', key:'nav.accounting'},
    { path:'/employees', icon:'👤', key:'nav.employees' },
  ],
  hospital: [
    { path:'/dashboard',    icon:'📊', key:'nav.dashboard'    },
    { path:'/patients',     icon:'🩺', key:'nav.patients'     },
    { path:'/appointments', icon:'📅', key:'nav.appointments' },
    { path:'/employees',    icon:'👨‍⚕️', key:'nav.doctors'    },
    null,
    { path:'/accounting',   icon:'💰', key:'nav.accounting'   },
    { path:'/inventory',    icon:'💊', key:'nav.pharmacy'     },
    { path:'/suppliers',    icon:'🚛', key:'nav.suppliers'    },
    { path:'/branches',     icon:'🏥', key:'nav.branches'     },
  ],
  clinic: [
    { path:'/dashboard',    icon:'📊', key:'nav.dashboard'    },
    { path:'/patients',     icon:'🩺', key:'nav.patients'     },
    { path:'/appointments', icon:'📅', key:'nav.appointments' },
    { path:'/employees',    icon:'👨‍⚕️', key:'nav.doctors'    },
    null,
    { path:'/accounting',   icon:'💰', key:'nav.accounting'   },
    { path:'/inventory',    icon:'💊', key:'nav.pharmacy'     },
  ],
  dental: [
    { path:'/dashboard',    icon:'📊', key:'nav.dashboard'    },
    { path:'/patients',     icon:'🦷', key:'nav.patients'     },
    { path:'/appointments', icon:'📅', key:'nav.appointments' },
    { path:'/employees',    icon:'👨‍⚕️', key:'nav.doctors'    },
    null,
    { path:'/accounting',   icon:'💰', key:'nav.accounting'   },
    { path:'/inventory',    icon:'📦', key:'nav.inventory'    },
  ],
  pharmacy: [
    { path:'/dashboard', icon:'📊', key:'nav.dashboard'  },
    { path:'/inventory', icon:'💊', key:'nav.medications'},
    { path:'/patients',  icon:'👥', key:'nav.customers'  },
    { path:'/suppliers', icon:'🚛', key:'nav.suppliers'  },
    null,
    { path:'/accounting',icon:'💰', key:'nav.accounting' },
    { path:'/employees', icon:'👤', key:'nav.employees'  },
  ],
  school: [
    { path:'/dashboard',  icon:'📊', key:'nav.dashboard'  },
    { path:'/students',   icon:'🎓', key:'nav.students'   },
    { path:'/grades',     icon:'📝', key:'nav.grades'     },
    { path:'/employees',  icon:'📚', key:'nav.teachers'   },
    null,
    { path:'/accounting', icon:'💰', key:'nav.fees'       },
    { path:'/branches',   icon:'🏫', key:'nav.branches'   },
  ],
  university: [
    { path:'/dashboard',  icon:'📊', key:'nav.dashboard'   },
    { path:'/students',   icon:'🎓', key:'nav.students'    },
    { path:'/grades',     icon:'📝', key:'nav.grades'      },
    { path:'/employees',  icon:'👨‍🏫', key:'nav.professors' },
    null,
    { path:'/accounting', icon:'💰', key:'nav.fees'        },
    { path:'/branches',   icon:'🎓', key:'nav.faculties'   },
  ],
  kindergarten: [
    { path:'/dashboard',  icon:'📊', key:'nav.dashboard'  },
    { path:'/students',   icon:'🧒', key:'nav.children'   },
    { path:'/employees',  icon:'👩‍🏫', key:'nav.teachers'  },
    null,
    { path:'/accounting', icon:'💰', key:'nav.fees'       },
  ],
  training_center: [
    { path:'/dashboard',  icon:'📊', key:'nav.dashboard'    },
    { path:'/students',   icon:'👥', key:'nav.trainees'     },
    { path:'/grades',     icon:'📜', key:'nav.certificates' },
    { path:'/employees',  icon:'👨‍🏫', key:'nav.trainers'   },
    null,
    { path:'/accounting', icon:'💰', key:'nav.accounting'   },
  ],
  restaurant: [
    { path:'/dashboard',           icon:'📊', key:'nav.dashboard' },
    { path:'/restaurant-orders',   icon:'🍽️', key:'nav.orders'    },
    { path:'/tables',              icon:'🪑', key:'nav.tables'    },
    { path:'/inventory',           icon:'🥩', key:'nav.inventory' },
    { path:'/suppliers',           icon:'🚛', key:'nav.suppliers' },
    null,
    { path:'/accounting',          icon:'💰', key:'nav.accounting'},
    { path:'/employees',           icon:'👤', key:'nav.employees' },
  ],
  cafe: [
    { path:'/dashboard',         icon:'📊', key:'nav.dashboard' },
    { path:'/restaurant-orders', icon:'☕', key:'nav.orders'    },
    { path:'/tables',            icon:'🪑', key:'nav.tables'    },
    { path:'/inventory',         icon:'📦', key:'nav.inventory' },
    null,
    { path:'/accounting',        icon:'💰', key:'nav.accounting'},
    { path:'/employees',         icon:'👤', key:'nav.employees' },
  ],
  salon_ladies: [
    { path:'/dashboard',           icon:'📊', key:'nav.dashboard'    },
    { path:'/salon-appointments',  icon:'💅', key:'nav.appointments' },
    { path:'/customers',           icon:'👥', key:'nav.customers'    },
    { path:'/employees',           icon:'✂️', key:'nav.staff'        },
    null,
    { path:'/accounting',          icon:'💰', key:'nav.accounting'   },
    { path:'/inventory',           icon:'🧴', key:'nav.products'     },
  ],
  salon_gents: [
    { path:'/dashboard',           icon:'📊', key:'nav.dashboard'    },
    { path:'/salon-appointments',  icon:'💈', key:'nav.appointments' },
    { path:'/employees',           icon:'✂️', key:'nav.staff'        },
    null,
    { path:'/accounting',          icon:'💰', key:'nav.accounting'   },
    { path:'/inventory',           icon:'🧴', key:'nav.products'     },
  ],
  spa: [
    { path:'/dashboard',           icon:'📊', key:'nav.dashboard'    },
    { path:'/salon-appointments',  icon:'🧖', key:'nav.appointments' },
    { path:'/customers',           icon:'👥', key:'nav.customers'    },
    { path:'/employees',           icon:'👤', key:'nav.therapists'   },
    null,
    { path:'/accounting',          icon:'💰', key:'nav.accounting'   },
  ],
  gym: [
    { path:'/dashboard',           icon:'📊', key:'nav.dashboard'  },
    { path:'/memberships',         icon:'🏋️', key:'nav.members'    },
    { path:'/salon-appointments',  icon:'📅', key:'nav.classes'    },
    { path:'/employees',           icon:'💪', key:'nav.trainers'   },
    null,
    { path:'/accounting',          icon:'💰', key:'nav.accounting' },
    { path:'/inventory',           icon:'🏋️', key:'nav.equipment'  },
  ],
  real_estate: [
    { path:'/dashboard',   icon:'📊', key:'nav.dashboard'  },
    { path:'/properties',  icon:'🏘️', key:'nav.properties' },
    { path:'/leases',      icon:'📄', key:'nav.leases'     },
    { path:'/customers',   icon:'👥', key:'nav.clients'    },
    null,
    { path:'/accounting',  icon:'💰', key:'nav.accounting' },
    { path:'/employees',   icon:'👤', key:'nav.employees'  },
  ],
  property_management: [
    { path:'/dashboard',   icon:'📊', key:'nav.dashboard'  },
    { path:'/properties',  icon:'🏢', key:'nav.properties' },
    { path:'/leases',      icon:'📄', key:'nav.leases'     },
    { path:'/customers',   icon:'👥', key:'nav.tenants'    },
    null,
    { path:'/accounting',  icon:'💰', key:'nav.accounting' },
    { path:'/employees',   icon:'👤', key:'nav.employees'  },
  ],
  construction_general: [
    { path:'/dashboard',       icon:'📊', key:'nav.dashboard'      },
    { path:'/projects',        icon:'🏗️', key:'nav.projects'       },
    { path:'/purchase-orders', icon:'🛒', key:'nav.purchaseOrders' },
    { path:'/suppliers',       icon:'🚛', key:'nav.suppliers'      },
    { path:'/inventory',       icon:'🔩', key:'nav.materials'      },
    null,
    { path:'/accounting',      icon:'💰', key:'nav.accounting'     },
    { path:'/employees',       icon:'👤', key:'nav.employees'      },
  ],
  freight: [
    { path:'/dashboard',       icon:'📊', key:'nav.dashboard'    },
    { path:'/customers',       icon:'👥', key:'nav.clients'      },
    { path:'/purchase-orders', icon:'📦', key:'nav.shipments'    },
    { path:'/employees',       icon:'🚗', key:'nav.drivers'      },
    null,
    { path:'/accounting',      icon:'💰', key:'nav.accounting'   },
    { path:'/suppliers',       icon:'🚛', key:'nav.suppliers'    },
  ],
  ngo: [
    { path:'/dashboard',   icon:'📊', key:'nav.dashboard'  },
    { path:'/customers',   icon:'❤️', key:'nav.donors'     },
    { path:'/projects',    icon:'🌱', key:'nav.programs'   },
    { path:'/employees',   icon:'👥', key:'nav.volunteers' },
    null,
    { path:'/accounting',  icon:'💰', key:'nav.accounting' },
  ],
};

// Aliases
['polyclinic','medical_lab','radiology','physiotherapy','optometry','veterinary','medical_spa'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.clinic; });
['catering'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.restaurant; });
['language_institute','driving_school','quran_institute'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.training_center; });
['mep','interior_design','car_workshop'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.construction_general; });
['real_estate_broker'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.real_estate; });
['delivery','warehouse_storage','transportation'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.freight; });
['waqf'].forEach(k => { NAV_CONFIGS[k] = NAV_CONFIGS.ngo; });
['spa'].forEach(k => { if (!NAV_CONFIGS[k]) NAV_CONFIGS[k] = NAV_CONFIGS.salon_ladies; });

const BOTTOM_NAV = [
  null,
  { path:'/chat',             icon:'💬', key:'nav.chat'        },
  { path:'/roles',            icon:'🛡️', key:'nav.roles'       },
  { path:'/company-settings', icon:'🏢', key:'nav.company'     },
  { path:'/settings',         icon:'⚙️', key:'settings.title'  },
];

export const getNavForIndustry = (industry) => {
  const specific = NAV_CONFIGS[industry] || NAV_CONFIGS._trade;
  return [...specific, ...BOTTOM_NAV];
};

export const getSectorColor = (industry) => {
  const colors = {
    hotel:'#ff6d00', furnished_apartments:'#ff8f00',
    hospital:'#e53935', clinic:'#c62828', dental:'#1976d2', pharmacy:'#00897b',
    medical_lab:'#6a1b9a', radiology:'#4527a0', physiotherapy:'#2e7d32',
    optometry:'#0277bd', veterinary:'#558b2f', medical_spa:'#c2185b',
    polyclinic:'#d32f2f',
    school:'#283593', university:'#1a237e', kindergarten:'#e91e63',
    training_center:'#1565c0', language_institute:'#006064',
    driving_school:'#37474f', quran_institute:'#004d40',
    restaurant:'#e65100', cafe:'#795548', catering:'#bf360c',
    salon_ladies:'#ad1457', salon_gents:'#1565c0', spa:'#6a1b9a',
    gym:'#7b1fa2', medical_spa:'#c2185b',
    real_estate:'#4e342e', property_management:'#5d4037', real_estate_broker:'#6d4c41',
    construction_general:'#e65100', mep:'#f57f17', interior_design:'#bf360c',
    freight:'#1b5e20', delivery:'#2e7d32', warehouse_storage:'#33691e',
    transportation:'#558b2f',
    ngo:'#c62828', waqf:'#004d40',
    trading_general:'#1a73e8', retail:'#00897b', wholesale:'#0288d1',
    ecommerce:'#f57c00', manufacturing:'#37474f',
  };
  return colors[industry] || '#1a73e8';
};

export const SECTOR_LABEL_OVERRIDES = {
  hospital:   { employees:'nav.doctors', customers:'nav.patients', projects:'nav.departments' },
  clinic:     { employees:'nav.doctors', customers:'nav.patients' },
  dental:     { employees:'nav.doctors', customers:'nav.patients' },
  school:     { employees:'nav.teachers', customers:'nav.students', projects:'nav.classes' },
  university: { employees:'nav.professors', customers:'nav.students', branches:'nav.faculties' },
  kindergarten:{ employees:'nav.teachers', customers:'nav.children' },
  training_center:{ employees:'nav.trainers', customers:'nav.trainees' },
  hotel:      { customers:'nav.guests', warehouses:'nav.rooms' },
  restaurant: { branches:'nav.sections', warehouses:'nav.kitchen' },
  gym:        { customers:'nav.members', employees:'nav.trainers' },
  salon_ladies:{ employees:'nav.staff', customers:'nav.clients' },
  salon_gents: { employees:'nav.staff', customers:'nav.clients' },
  spa:         { employees:'nav.therapists', customers:'nav.clients' },
  real_estate: { customers:'nav.clients' },
  property_management:{ customers:'nav.tenants' },
  ngo:         { customers:'nav.donors', employees:'nav.volunteers', projects:'nav.programs' },
  freight:     { customers:'nav.clients', employees:'nav.drivers' },
};
