import React from 'react';
import { Chip, Box, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import SectorPage from './SectorPage';
const Tables = () => {
  const { t, i18n } = useTranslation();
  const AR = i18n.language === 'ar';
  const CONFIGS = {
    MembershipsPage: { endpoint:'/api/memberships', icon:'🏋️', title:AR?'الأعضاء':'Members', addLabel:AR?'عضو جديد':'New Member', itemLabel:AR?'عضو':'member', searchFields:['member.name','member.phone','memberNumber'], emptyForm:{'member.name':'','member.phone':'','member.gender':'male','plan':'','planType':'monthly','startDate':'','endDate':'','amount':0,'discount':0,'status':'active','notes':''}, validate:(f,AR)=>(!f['member.name']?.trim()?(AR?'الاسم مطلوب':'Name required'):null), columns:[{key:'memberNumber',label:AR?'رقم العضو':'#',render:(i)=><Typography variant="caption" sx={{fontFamily:'monospace'}}>{i.memberNumber||'—'}</Typography>},{key:'member',label:AR?'العضو':'Member',render:(i)=><Box><Typography variant="body2" fontWeight={600}>{i.member?.name||'—'}</Typography><Typography variant="caption" color="text.secondary">{i.member?.phone}</Typography></Box>},{key:'plan',label:AR?'الخطة':'Plan',render:(i)=><Chip label={i.plan||'—'} size="small" sx={{fontSize:'0.7rem'}}/>},{key:'endDate',label:AR?'الانتهاء':'Expiry',render:(i)=><Typography variant="body2">{i.endDate?new Date(i.endDate).toLocaleDateString('ar-SA'):'—'}</Typography>},{key:'status',label:AR?'الحالة':'Status',render:(i)=><Chip label={AR?{active:'نشط',expired:'منتهي',frozen:'مجمد',cancelled:'ملغى'}[i.status]:i.status} color={{active:'success',expired:'error',frozen:'info',cancelled:'default'}[i.status]||'default'} size="small" sx={{fontSize:'0.7rem'}}/>}],
      formTabs:[{label:AR?'بيانات العضو':'Member Info',fields:[{key:'member.name',label:AR?'الاسم *':'Name *',width:6,required:true},{key:'member.phone',label:AR?'الهاتف *':'Phone *',width:6,required:true},{key:'member.gender',label:AR?'الجنس':'Gender',width:4,type:'select',options:[{value:'male',label:AR?'ذكر':'Male'},{value:'female',label:AR?'أنثى':'Female'}]},{key:'plan',label:AR?'الخطة':'Plan',width:4},{key:'planType',label:AR?'نوع الاشتراك':'Plan Type',width:4,type:'select',options:[{value:'monthly',label:AR?'شهري':'Monthly'},{value:'quarterly',label:AR?'ربع سنوي':'Quarterly'},{value:'semi_annual',label:AR?'نصف سنوي':'Semi-Annual'},{value:'annual',label:AR?'سنوي':'Annual'}]},{key:'startDate',label:AR?'تاريخ البداية *':'Start *',width:6,type:'date',required:true},{key:'endDate',label:AR?'تاريخ الانتهاء *':'End *',width:6,type:'date',required:true},{key:'amount',label:AR?'الرسوم (ر.س)':'Fee (SAR)',width:4,type:'number'},{key:'discount',label:AR?'الخصم':'Discount',width:4,type:'number'},{key:'status',label:AR?'الحالة':'Status',width:4,type:'select',options:[{value:'active',label:AR?'نشط':'Active'},{value:'frozen',label:AR?'مجمد':'Frozen'},{value:'expired',label:AR?'منتهي':'Expired'},{value:'cancelled',label:AR?'ملغى':'Cancelled'}]},{key:'notes',label:AR?'ملاحظات':'Notes',width:12,type:'textarea'}]}]},
    TablesPage: { endpoint:'/api/tables', icon:'🪑', title:AR?'الطاولات':'Tables', addLabel:AR?'طاولة جديدة':'New Table', itemLabel:AR?'طاولة':'table', searchFields:['number','section'], emptyForm:{number:'',capacity:4,section:'',status:'available',notes:'',isActive:true}, validate:(f,AR)=>(!f.number?.trim()?(AR?'رقم الطاولة مطلوب':'Table number required'):null), columns:[{key:'number',label:AR?'رقم الطاولة':'Table #',render:(i)=><Typography variant="body2" fontWeight={700}>{i.number}</Typography>},{key:'capacity',label:AR?'السعة':'Capacity',render:(i)=><Typography variant="body2">{i.capacity} 👥</Typography>},{key:'section',label:AR?'القسم':'Section',render:(i)=><Typography variant="body2">{i.section||'—'}</Typography>},{key:'status',label:AR?'الحالة':'Status',render:(i)=><Chip label={AR?{available:'متاح',occupied:'مشغول',reserved:'محجوز',cleaning:'تنظيف'}[i.status]:i.status} color={{available:'success',occupied:'error',reserved:'warning',cleaning:'info'}[i.status]||'default'} size="small" sx={{fontSize:'0.7rem'}}/>}],
      formTabs:[{label:AR?'بيانات الطاولة':'Table Details',fields:[{key:'number',label:AR?'رقم الطاولة *':'Table # *',width:4,required:true},{key:'capacity',label:AR?'السعة (أشخاص)':'Capacity',width:4,type:'number'},{key:'section',label:AR?'القسم / المنطقة':'Section',width:4},{key:'status',label:AR?'الحالة':'Status',width:6,type:'select',options:[{value:'available',label:AR?'متاح':'Available'},{value:'occupied',label:AR?'مشغول':'Occupied'},{value:'reserved',label:AR?'محجوز':'Reserved'},{value:'cleaning',label:AR?'تنظيف':'Cleaning'}]},{key:'notes',label:AR?'ملاحظات':'Notes',width:12,type:'textarea'}]}]},
    RestaurantOrdersPage: { endpoint:'/api/restaurant-orders', icon:'🍽️', title:AR?'الطلبات':'Orders', addLabel:AR?'طلب جديد':'New Order', itemLabel:AR?'طلب':'order', searchFields:['orderNumber','customerName'], emptyForm:{orderNumber:'',type:'dine_in',customerName:'',customerPhone:'','items.0.name':'','items.0.quantity':1,'items.0.unitPrice':0,status:'open',paymentMethod:'cash',notes:''}, validate:(f,AR)=>null, columns:[{key:'orderNumber',label:AR?'رقم الطلب':'Order #',render:(i)=><Typography variant="caption" sx={{fontFamily:'monospace'}}>{i.orderNumber||i._id?.slice(-6)}</Typography>},{key:'type',label:AR?'النوع':'Type',render:(i)=><Chip label={AR?{dine_in:'داخل',takeaway:'خارج',delivery:'توصيل'}[i.type]:i.type} size="small" sx={{fontSize:'0.7rem'}}/>},{key:'total',label:AR?'الإجمالي':'Total',render:(i)=><Typography variant="body2" fontWeight={700}>{(i.total||0).toLocaleString()} {AR?'ر.س':'SAR'}</Typography>},{key:'status',label:AR?'الحالة':'Status',render:(i)=><Chip label={AR?{open:'مفتوح',preparing:'يُحضَّر',ready:'جاهز',served:'قُدِّم',paid:'مدفوع',cancelled:'ملغى'}[i.status]:i.status} color={{open:'warning',preparing:'info',ready:'primary',served:'secondary',paid:'success',cancelled:'error'}[i.status]||'default'} size="small" sx={{fontSize:'0.7rem'}}/>}],
      formTabs:[{label:AR?'تفاصيل الطلب':'Order Details',fields:[{key:'type',label:AR?'نوع الطلب':'Type',width:4,type:'select',options:[{value:'dine_in',label:AR?'داخل المطعم':'Dine In'},{value:'takeaway',label:AR?'خارج':'Takeaway'},{value:'delivery',label:AR?'توصيل':'Delivery'}]},{key:'customerName',label:AR?'اسم العميل':'Customer',width:4},{key:'customerPhone',label:AR?'الهاتف':'Phone',width:4},{key:'items.0.name',label:AR?'اسم الطبق':'Item Name',width:5},{key:'items.0.quantity',label:AR?'الكمية':'Qty',width:3,type:'number'},{key:'items.0.unitPrice',label:AR?'السعر':'Price',width:4,type:'number'},{key:'status',label:AR?'الحالة':'Status',width:4,type:'select',options:[{value:'open',label:AR?'مفتوح':'Open'},{value:'preparing',label:AR?'يُحضَّر':'Preparing'},{value:'ready',label:AR?'جاهز':'Ready'},{value:'served',label:AR?'قُدِّم':'Served'},{value:'paid',label:AR?'مدفوع':'Paid'},{value:'cancelled',label:AR?'ملغى':'Cancelled'}]},{key:'paymentMethod',label:AR?'الدفع':'Payment',width:4,type:'select',options:[{value:'cash',label:AR?'نقد':'Cash'},{value:'card',label:AR?'بطاقة':'Card'},{value:'transfer',label:AR?'تحويل':'Transfer'}]},{key:'notes',label:AR?'ملاحظات':'Notes',width:12,type:'textarea'}]}]},
    GradesPage: { endpoint:'/api/grades', icon:'📝', title:AR?'الدرجات':'Grades', addLabel:AR?'درجة جديدة':'New Grade', itemLabel:AR?'درجة':'grade', searchFields:['subject','semester'], emptyForm:{student:'',subject:'',grade:0,gradeType:'exam',semester:'',academicYear:'',notes:''}, validate:(f,AR)=>(!f.subject?.trim()?(AR?'المادة مطلوبة':'Subject required'):null), columns:[{key:'subject',label:AR?'المادة':'Subject',render:(i)=><Typography variant="body2" fontWeight={600}>{i.subject}</Typography>},{key:'grade',label:AR?'الدرجة':'Grade',render:(i)=><Typography variant="body2" fontWeight={700} sx={{color:i.grade>=60?'success.main':'error.main'}}>{i.grade}/100</Typography>},{key:'gradeType',label:AR?'النوع':'Type',render:(i)=><Chip label={AR?{exam:'اختبار',quiz:'واجب',assignment:'تكليف',midterm:'نصفي',final:'نهائي'}[i.gradeType]:i.gradeType} size="small" sx={{fontSize:'0.7rem'}}/>},{key:'semester',label:AR?'الفصل':'Semester',render:(i)=><Typography variant="body2">{i.semester||'—'}</Typography>}],
      formTabs:[{label:AR?'بيانات الدرجة':'Grade Details',fields:[{key:'subject',label:AR?'المادة *':'Subject *',width:6,required:true},{key:'gradeType',label:AR?'نوع التقييم':'Assessment Type',width:6,type:'select',options:[{value:'exam',label:AR?'اختبار':'Exam'},{value:'quiz',label:AR?'اختبار قصير':'Quiz'},{value:'assignment',label:AR?'واجب':'Assignment'},{value:'midterm',label:AR?'منتصف الفصل':'Midterm'},{value:'final',label:AR?'نهائي':'Final'},{value:'project',label:AR?'مشروع':'Project'}]},{key:'grade',label:AR?'الدرجة (0-100)':'Grade (0-100)',width:4,type:'number'},{key:'semester',label:AR?'الفصل الدراسي':'Semester',width:4},{key:'academicYear',label:AR?'العام الدراسي':'Academic Year',width:4},{key:'notes',label:AR?'ملاحظات':'Notes',width:12,type:'textarea'}]}]},
  };
  return <SectorPage config={CONFIGS['TablesPage']} />;
};
export default Tables;
